### ISSUE TITLE
New release tag

### ISSUE THREAD

**Issue by uny** [nvzqz/FileKit#19]
I would like a release tag including @Dschee 's contributions https://github.com/nvzqz/FileKit/pull/18 .

**Comment by Techprimate** [comment]
+1

**Comment by nvzqz** [comment]
I'm going to look through previous commits to evaluate whether or not some are API-breaking or not. If they are, the next release will be 3.0.0, otherwise 2.1.0. Plans for 3.0.0 include cleaning up some ambiguities and making the project SPM-compatible. Apologies for not getting around to an update sooner!

**Comment by Dschee** [comment]
Couldn't you simply make a release from commit 020e322f586d573668a846a5f2b9eee26beb2ca2 tagged as version 2.1 or 2.0.1? It could take a while until 3.0 is finished – it's already been a while since my fixes and I'm still waiting for a new release which. This holds back my [CSVImporter] framework to be released via CocoaPods (since I can't set my fork as a dependency in the .podspec I have to wait for a release here).

Would be great to get an updated release soon without the breaking changes. Otherwise I'll have to create a separate trunk on CocoaPods which I'd rather like to prevent.

**Comment by Dschee** [comment]
Since I didn't get an answer for nearly two weeks now and this issue is already open for several months, **I released a new version myself**. Until a new version of FileKit is officially released replace you entry `pod "FileKit", "~> 2.0"` with `pod "Dschee-FileKit", "~> 2.1.1"` – that should get you the most current state of the develop branch as of now using my fork [here](https://github.com/Dschee/FileKit).
