### ISSUE TITLE
File System Watching Documentation

### ISSUE THREAD

**Issue by RohanNagar** [nvzqz/FileKit#25]
I read the release notes for v3.0.0, and "File system watching" caught my eye. I need to do file system watching in my application so that I can update a CollectionView as the contents of a directory change.

I don't see where usage of this feature is documented. Can you point me to where it is, or if there isn't any documentation, can you please provide some? I would love to take advantage of this feature.

Thanks!

**Comment by nvzqz** [comment]
I'm actually not quite familiar with the implementation since it was made by other contributors but you can find `Path`'s `watch` method [here](https://github.com/nvzqz/FileKit/blob/eaf3a98604028b5afe51224e6b60ebaf33f4197e/Sources/DispatchWatcher.swift#L342). I don't like having two separate watch methods for OS X (watch2 isn't a good name), so that'll be cleaned up for v4.0.0.
